data:
  corpus: # Pass to dataloader
    # The following depends on corpus
    name: "Tedlium" # Specify corpus
    path: "/home/s1870697/MLP_Group_Project/src/Data/TEDLIUM_release-3/legacy"
    train_split: ["train/sph/t3_commoncrawl-9pc.en"] # Official LM src from LibriSpeech
    dev_split: ["dev"]
    bucketing: True
    batch_size: 16
  text:
    mode: "character" # 'character'/'word'/'subword'
    vocab_file: "tests/sample_data/character.vocab"

hparas: # Experiment hyper-parameters
  valid_step: 10000
  max_step: 100000000
  optimizer: "Adam"
  lr: 0.0001
  eps: 0.00000001
  lr_scheduler: "fixed" # 'fixed'/'warmup'

model: # Model architecture
  emb_tying: False # https://arxiv.org/pdf/1608.05859.pdf
  emb_dim: 256
  module: "LSTM" # 'LSTM'/'GRU'
  dim: 256
  n_layers: 2
  dropout: 0.2
